# Generated by Django 3.2.4 on 2021-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('picture', models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='Картинка')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
