# Generated by Django 3.2.4 on 2021-06-16 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Контент'),
            preserve_default=False,
        ),
    ]
