# Generated by Django 3.2.4 on 2021-06-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210618_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news'),
        ),
    ]
