# Generated by Django 3.2.4 on 2021-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210619_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text2',
            field=models.TextField(verbose_name='text'),
        ),
    ]
