# Generated by Django 3.2.4 on 2021-06-24 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_news_text2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', ckeditor.fields.RichTextField(verbose_name='Богослужения')),
            ],
            options={
                'verbose_name': 'Богослужения',
            },
        ),
    ]
