# Generated by Django 3.2.4 on 2021-06-24 10:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Churches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='media/churches', verbose_name='Фотография')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Храм',
                'verbose_name_plural': 'Храмы',
            },
        ),
    ]
