# Generated by Django 3.2.4 on 2021-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_churches'),
    ]

    operations = [
        migrations.AddField(
            model_name='churches',
            name='slug',
            field=models.SlugField(default='some-text', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
