# Generated by Django 3.2.4 on 2021-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_churches_short_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churches',
            options={'ordering': ['id'], 'verbose_name': 'Храм', 'verbose_name_plural': 'Храмы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Богослужения', 'verbose_name_plural': 'Богослужения'},
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='churches',
            name='short_text',
            field=models.TextField(max_length=350, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='title',
            field=models.CharField(db_index=True, default='image', max_length=150),
        ),
    ]
