# Generated by Django 3.2.6 on 2022-01-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220113_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagepicture',
            options={'ordering': ['id'], 'verbose_name': 'Главная картинка страницы', 'verbose_name_plural': 'Главные картинки страниц'},
        ),
        migrations.AddField(
            model_name='mainpagepicture',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название картинки'),
        ),
    ]
