# Generated by Django 3.2.6 on 2022-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220203_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churches',
            name='keywords_meta',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords_meta',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='keywords_meta',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
    ]
